-- AlterTable
ALTER TABLE `events` ADD COLUMN `username` VARCHAR(191) NULL,
    ALTER COLUMN `title` DROP DEFAULT,
    MODIFY `date` DATETIME(3) NOT NULL,
    ALTER COLUMN `filePath` DROP DEFAULT,
    MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedAt` DATETIME(3) NOT NULL;

-- AddForeignKey
ALTER TABLE `events` ADD CONSTRAINT `events_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
